/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dnsrpc_CONSTANTS_H
#define dnsrpc_CONSTANTS_H

#include "dnsrpc_types.h"

namespace rpc { namespace yamutech { namespace com {

class dnsrpcConstants {
 public:
  dnsrpcConstants();

};

extern const dnsrpcConstants g_dnsrpc_constants;

}}} // namespace

#endif
