/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dnsrpc_constants.h"

namespace rpc { namespace yamutech { namespace com {

const dnsrpcConstants g_dnsrpc_constants;

dnsrpcConstants::dnsrpcConstants() {
}

}}} // namespace

